### PR TITLE
US9_AccessCorrectModules

### PR DESCRIPTION
**Pull request by Asmafzal**
I finished my US9.  Can you review and merge.

### CODE REVIEW

**Comment by Sabihagecu** [comment]
cool code

**Comment by Sabihagecu** [comment]
cool code

**Comment by Sabihagecu** [comment]
cool code

**Review by Ariuntuul — APPROVED** [review]
I have reviewed and looks all great to me.

**Comment by Sabihagecu** [comment]
cool code

**Comment by mdokan** [comment]
Cool code

**Pull request merged**
